# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  unit-tests:
      name: Unit tests
      runs-on: ubuntu-latest
      timeout-minutes: 10
      steps:
          - uses: actions/checkout@v2
          - uses: gradle/wrapper-validation-action@v1
          - uses: actions/setup-java@v1
            with:
                java-version: 11
          - uses: actions/cache@v2
            with:
                path: ~/.gradle/caches
                key: gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/src/main/kotlin/Library.kt') }}

          - name: Unit tests
            run: ./gradlew testDebugUnitTest
  
  instrumentation-tests:
      name: Instrumentation tests
      runs-on: macOS-latest
      timeout-minutes: 60
      strategy:
          fail-fast: true
          matrix:
              api-level: [21, 25, 29]
      steps:
          - uses: actions/checkout@v2
          - uses: gradle/wrapper-validation-action@v1
          - uses: actions/setup-java@v1
            with:
                java-version: 11

          # Restore the cache.
          # Intentionally don't set 'restore-keys' so the cache never contains redundant dependencies.
          - uses: actions/cache@v2
            with:
                path: ~/.gradle/caches
                key: gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/src/main/kotlin/Library.kt') }}

          - name: Instrumentation tests
            uses: reactivecircus/android-emulator-runner@v2
            with:
                api-level: ${{ matrix.api-level }}
                arch: x86
                script: ./gradlew connectedDebugAndroidTest
